let btn = document.getElementById('button')
let color = document.getElementById('color')
let text = document.getElementById('text')
let link = document.getElementById('link')
let logobig = document.getElementById('logo-big')
let logosmall = document.getElementById('logo-small')
let header = document.getElementById('header')
let tabsright = document.getElementById('tabs-right')
let tabsleft = document.getElementById('tabs-left')

let tabscontent1 = document.getElementById('tabs-content1')
let tabscontent2 = document.getElementById('tabs-content2')
let tabscontent3 = document.getElementById('tabs-content3')
let tabscontent4 = document.getElementById('tabs-content4')
let donate = document.getElementById('donate')



btn.addEventListener('click', function onClick() {
    if(Array.from(btn.classList).includes("dark")){
        btn.classList.remove("dark")
        btn.classList.add("light")
        color.classList.remove("dark")
        color.classList.add("light")
        text.classList.remove("dark")
        text.classList.add("light")
        link.classList.remove("dark")
        link.classList.add("light")
        logobig.classList.remove("dark")
        logobig.classList.add("light")
        logosmall.classList.remove("dark")
        logosmall.classList.add("light")
        header.classList.remove("dark")
        header.classList.add("light")
        tabsright.classList.remove("dark")
        tabsright.classList.add("light")
        tabsleft.classList.remove("dark")
        tabsleft.classList.add("light")
        donate.classList.remove("dark")
        donate.classList.add("light")

        tabscontent1.classList.remove("dark")
        tabscontent1.classList.add("light")
        tabscontent2.classList.remove("dark")
        tabscontent2.classList.add("light")
        tabscontent3.classList.remove("dark")
        tabscontent3.classList.add("light")
        tabscontent4.classList.remove("dark")
        tabscontent4.classList.add("light")
    }
    else {
        btn.classList.remove("light")
        btn.classList.add("dark")
        color.classList.remove("light")
        color.classList.add("dark")
        text.classList.remove("light")
        text.classList.add("dark")
        link.classList.remove("light")
        link.classList.add("dark")
        logobig.classList.remove("light")
        logobig.classList.add("dark")
        logosmall.classList.remove("light")
        logosmall.classList.add("dark")
        header.classList.remove("light")
        header.classList.add("dark")
        tabsright.classList.remove("light")
        tabsright.classList.add("dark")
        tabsleft.classList.remove("light")
        tabsleft.classList.add("dark")
        donate.classList.remove("light")
        donate.classList.add("dark")

        tabscontent1.classList.remove("light")
        tabscontent1.classList.add("dark")
        tabscontent2.classList.remove("light")
        tabscontent2.classList.add("dark")
        tabscontent3.classList.remove("light")
        tabscontent3.classList.add("dark")
        tabscontent4.classList.remove("light")
        tabscontent4.classList.add("dark")


    }
});